spring.application.name=worker_ms

spring.cloud.aws.region.static=us-east-1
spring.cloud.aws.credentials.access-key=test
spring.cloud.aws.credentials.secret-key=test
spring.cloud.aws.sqs.endpoint=http://localhost:4566
spring.cloud.aws.s3.endpoint=http://localhost:4566
spring.cloud.aws.s3.path-style-access-enabled=true

app.sqs.process-queue=process-queue
app.sqs.status-queue=video-status-queue
app.processing.fps=1
app.processing.work-dir=${java.io.tmpdir}/worker-ms
