#!/bin/sh
set -eu

email="codex-$(date +%s)@example.com"
password="senha123"
name="Codex Local Test"
sample="/tmp/codex-sample.mp4"
download="/tmp/codex-download.zip"

json_get() {
  key="$1"
  sed -n "s/.*\"$key\"[[:space:]]*:[[:space:]]*\"\([^\"]*\)\".*/\1/p"
}

printf "sample video content %s" "$(date)" > "$sample"

printf "Waiting services"
for i in $(seq 1 60); do
  auth_code=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8082/auth/swagger-ui.html || true)
  localstack_code=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:4566/_localstack/health || true)
  mgmt_code=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8080/videos/status || true)

  if { [ "$auth_code" = "200" ] || [ "$auth_code" = "302" ]; } && [ "$localstack_code" = "200" ] && { [ "$mgmt_code" = "401" ] || [ "$mgmt_code" = "403" ]; }; then
    printf " ready\n"
    break
  fi

  if [ "$i" = "60" ]; then
    printf "\nServices not ready: auth=%s localstack=%s management=%s\n" "$auth_code" "$localstack_code" "$mgmt_code"
    exit 1
  fi

  printf "."
  sleep 1
done

create_body=$(printf '{"name":"%s","email":"%s","password":"%s"}' "$name" "$email" "$password")
create_resp=$(curl -s -X POST http://localhost:8082/auth/users -H "Content-Type: application/json" -d "$create_body")
user_id=$(printf "%s" "$create_resp" | json_get id)
if [ -z "$user_id" ]; then
  printf "Create user failed: %s\n" "$create_resp"
  exit 1
fi
printf "Created user: %s\n" "$user_id"

login_body=$(printf '{"email":"%s","password":"%s"}' "$email" "$password")
login_resp=$(curl -s -X POST http://localhost:8082/auth/login -H "Content-Type: application/json" -d "$login_body")
token=$(printf "%s" "$login_resp" | json_get token)
if [ -z "$token" ]; then
  printf "Login failed: %s\n" "$login_resp"
  exit 1
fi
printf "Login OK, token length: %s\n" "${#token}"

upload_resp=""
for _ in $(seq 1 20); do
  upload_resp=$(curl -s -X POST http://localhost:8080/videos -H "Authorization: Bearer $token" -F "file=@$sample;type=video/mp4")
  video_id=$(printf "%s" "$upload_resp" | json_get videoProcessId)
  if [ -n "$video_id" ]; then
    break
  fi
  sleep 1
done

video_id=$(printf "%s" "$upload_resp" | json_get videoProcessId)
file_name=$(printf "%s" "$upload_resp" | json_get fileName)
zip_key=$(printf "%s" "$upload_resp" | json_get zipStorageKey)
zip_name=$(printf "%s" "$upload_resp" | json_get zipFileName)
if [ -z "$video_id" ] || [ -z "$file_name" ] || [ -z "$zip_key" ] || [ -z "$zip_name" ]; then
  printf "Upload failed: %s\n" "$upload_resp"
  exit 1
fi
printf "Upload OK: video=%s file=%s zip=%s\n" "$video_id" "$file_name" "$zip_key"

process_queue_resp=$(curl -s -X POST http://localhost:4566/000000000000/process-queue \
  -H "Content-Type: application/x-www-form-urlencoded" \
  -d "Action=ReceiveMessage" -d "Version=2012-11-05" -d "MaxNumberOfMessages=10")
if printf "%s" "$process_queue_resp" | grep -q "$video_id"; then
  printf "Process queue has video event\n"
else
  printf "Process queue check did not find event; continuing because ReceiveMessage can consume messages.\n"
fi

curl -s -X PUT "http://localhost:4566/videos-bucket/$zip_key" \
  -H "Content-Type: application/zip" \
  --data-binary "fake zip generated by codex test" >/dev/null
printf "Fake ZIP uploaded to S3\n"

status_body=$(printf '{"videoProcessId":"%s","status":"PROCESSED","zipStorageKey":"%s","zipFileName":"%s"}' "$video_id" "$zip_key" "$zip_name")
curl -s -X POST http://localhost:4566/000000000000/video-status-queue \
  -H "Content-Type: application/x-www-form-urlencoded" \
  -d "Action=SendMessage" -d "Version=2012-11-05" --data-urlencode "MessageBody=$status_body" >/dev/null
printf "PROCESSED status sent\n"

status_resp=""
for _ in $(seq 1 20); do
  status_resp=$(curl -s -H "Authorization: Bearer $token" "http://localhost:8080/videos/$file_name/status")
  if printf "%s" "$status_resp" | grep -q "PROCESSED"; then
    break
  fi
  sleep 1
done
if ! printf "%s" "$status_resp" | grep -q "PROCESSED"; then
  printf "Status did not become PROCESSED: %s\n" "$status_resp"
  exit 1
fi
printf "Status OK: PROCESSED\n"

download_code=$(curl -s -L -o "$download" -w "%{http_code}" \
  -H "Authorization: Bearer $token" \
  "http://localhost:8080/videos/$file_name/download")
if [ "$download_code" != "200" ]; then
  printf "Download failed with HTTP %s\n" "$download_code"
  exit 1
fi
bytes=$(wc -c < "$download" | tr -d " ")
printf "Download OK: %s bytes\n" "$bytes"
printf "E2E OK email=%s user=%s video=%s\n" "$email" "$user_id" "$video_id"
